# application.yml
spring:
  profiles:
    active: local # 디폴트 환경
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: govlepel@$&

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /docs/swagger-ui.html
    displayRequestDuration: true
    groups-order: DESC
